export enum ActionType {
    SET_QUESTIONS = 'SET_QUESTIONS',
    GET_QUESTIONS = 'GET_QUESTIONS',
    DISPLAY_ERROR = 'DISPLAY_ERROR',
    NEXT_QUESTION = 'NEXT_QUESTION',
    RESTART_QUIZ = 'RESTART_QUIZ',
}
